/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui.infosheets;

import processes.helpers.CommonNamesWriter;
import processes.helpers.ModalityPanel;
import processes.helpers.WindowStatus;
import ui.functions.MolarMassCalculator;

/**
 *
 * @author jared
 */
public class CommonElements extends javax.swing.JFrame {
    
    final private String commonElementsStatus = "Common Elements Status";
    
    private String toAdd;
    private MolarMassCalculator theParent;

    /**
     * Creates new form CommonElements
     */
    public CommonElements(MolarMassCalculator parent) {
        theParent = parent;
        toAdd = null;
        initComponents();
        this.setTitle("Common Names and Formulas");
    }
    
    public CommonElements() {
        theParent = null;
        toAdd = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addOne = new javax.swing.JMenuItem();
        addMultiple = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setBackground(new java.awt.Color(191, 191, 191));
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage((getClass().getClassLoader().getResource("resources/icon.png"))));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        table.setModel(new javax.swing.table.DefaultTableModel(CommonNamesWriter.getCommonNames(), CommonNamesWriter.DEFAULT_HEADERS));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        addButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addButton.setText("Add to Formula");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        addOne.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        addOne.setText("Add One Compound");
        addOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOneActionPerformed(evt);
            }
        });
        jMenu1.add(addOne);

        addMultiple.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        addMultiple.setText("Add Multiple Compounds");
        addMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMultipleActionPerformed(evt);
            }
        });
        jMenu1.add(addMultiple);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //probably should delete this, dont need it
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        WindowStatus.writeFile("false", commonElementsStatus);
    }//GEN-LAST:event_formWindowClosing

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int row = table.rowAtPoint(evt.getPoint());
        int col = 1; // the middle column with the element formula
        
        // get ready to add the formula of the selected row of the table inside parentheses
        toAdd = "(" + table.getValueAt(row, col).toString() + ")";
    }//GEN-LAST:event_tableMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // add the formula surrounded by parentheses of the currently selected row as long as one is selected
        if (toAdd != null && theParent != null) {
            theParent.addText(toAdd);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void addMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMultipleActionPerformed
        ModalityPanel p = new ModalityPanel(this);
    }//GEN-LAST:event_addMultipleActionPerformed

    private void addOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOneActionPerformed
        ModalityPanel p = new ModalityPanel(this, 1);
    }//GEN-LAST:event_addOneActionPerformed



    /**
     * set the MolarMassCalulator object the text gets added to
     * @param parent the MolarMassCalculator object to add text to
     */
    public void setParent(MolarMassCalculator parent) {
        theParent = parent;
    }
    
    /**
     * add multiple compounds to the formula page
     * @param i the number of new compounds to add
     */
    public void addMultiple(int i) {
        ModalityPanel p = new ModalityPanel(this, i);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JMenuItem addMultiple;
    private javax.swing.JMenuItem addOne;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
