/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui.infosheets;

import processes.helpers.WindowStatus;

/**
 *
 * @author jared
 */
public class SolubilityRules extends javax.swing.JFrame {
    
    final private String solubilityRulesStatus = "Solubility Rules Status";

    /**
     * Creates new form SolubilityRules
     */
    public SolubilityRules() {
        initComponents();
        this.setTitle("Solubility Rules");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("<html>         <h2>Solubility Rules of Salts in Water</h2>     <p>         <h4>1. Most nitrate (NO3-) salts are soluble.</h4>         <h4>2. Most salts containing the alkali metal ions (Li+, Na+, K+, Cs+, Rb+) and the ammonium ion(NH4+) are soluble</h4>         <h4>3. Most chloride, bromide, and iodide salts are soluble.  Notable exceptions are salts containing the ions Ag +,  Pb 2+, and Hg 2+.</h4>         <h4>4.Most sulfate salts are soluble.  Notable exceptions are BaSO4, PbSO4, Hg2SO4, and CaSO4</h4>         <h4>5. Most hydroxide salts are only slightly soluble.  The important soluble hydroxides are NaOH and KOH.  The compounds Ba(OH)2, Sr(OH)2, and Ca(OH)2 are marginally soluble.</h4>         <h4>6. Most sulfide(S   2-), carbonate(CO3   2-), chromate(CrO4   2-) and phosphate(PO4   3-) salts are only slightly soluble.</h4>     </p> </html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        WindowStatus.writeFile("false", solubilityRulesStatus);
    }//GEN-LAST:event_formWindowClosing



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
