/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package processes.helpers;

import ui.infosheets.CommonElements;

/**
 *
 * @author jared
 */
public class EnterNumber extends javax.swing.JPanel {
    
    private ModalityPanel owner;
    private CommonElements parent;

    /**
     * Creates new form EnterNumber
     */
    public EnterNumber() {
        initComponents();
    }
    
    /**
     * Create a new form EnterNumber with a parent and owner
     * @param parent the CommonElements object that created the modality panel what created the EnterNumber form
     * @param owner the ModalityPanel object that created the EnterNumber form
     */
    public EnterNumber(CommonElements parent, ModalityPanel owner) {
        this.parent = parent;
        this.owner = owner;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toAdd = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();

        toAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toAddActionPerformed(evt);
            }
        });

        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirm)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(toAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(confirm))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        String text = toAdd.getText();
        // get the number in the text box
        if (Formatting.isOnlyDigits(text) && !text.equals("")) {
            int i = Integer.parseInt(text);
            owner.dispose();
            parent.addMultiple(i);
        }
        // if there was no number, empty the text box
        else {
            toAdd.setText("");
        }
    }//GEN-LAST:event_confirmActionPerformed

    private void toAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toAddActionPerformed
        String text = toAdd.getText();
        // get the number in the text box
        if (Formatting.isOnlyDigits(text) && !text.equals("")) {
            int i = Integer.parseInt(text);
            if (i > 0) {
                owner.dispose();
                parent.addMultiple(i);
            }
            else {
                toAdd.setText("");
            }
        }
        // if there was no number, empty the text box
        else {
            toAdd.setText("");
        }
    }//GEN-LAST:event_toAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm;
    private javax.swing.JTextField toAdd;
    // End of variables declaration//GEN-END:variables
}
